import type {Metadata} from "next";
import LocalFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import {SessionProvider} from "next-auth/react";

const iranSans = LocalFont({
    src: [
        {
            path: "/fonts/IRANSansXFaNum-Regular.woff2",
            weight: '400',
            style: 'normal',
        }, {
            path: "/fonts/IRANSansXFaNum-Black.woff2",
            weight: '900',
            style: 'bolder',
        }, {
            path: "/fonts/IRANSansXFaNum-Bold.woff2",
            weight: '800',
            style: 'bold',
        },
        {
            path: "/fonts/IRANSansXFaNum-DemiBold.woff2",
            weight: '600',
            style: 'semibold',
        },
        {
            path: "/fonts/IRANSansXFaNum-Medium.woff2",
            weight: '500',
            style: 'medium',
        },
        {
            path: "/fonts/IRANSansXFaNum-Medium.woff2",
            weight: '300',
            style: 'light',
        },
    ]
})

export const metadata: Metadata = {
    title: "Prisma",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">
        <SessionProvider>

            <body
                className={`${iranSans.className} `}
            >
            <Header/>
            {children}
            <Footer/>
            </body>
        </SessionProvider>
        </html>
    );
}
